version: '2'
services:
    learningjhipster-app:
        image: learningjhipster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://learningjhipster-mysql:3306/learningjhipster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    learningjhipster-mysql:
        extends:
            file: mysql.yml
            service: learningjhipster-mysql
